import React, { useState, useEffect, useRef } from "react";

export default function App() {
  const [started, setStarted] = useState(false);
    const [accepted, setAccepted] = useState(false);
      const [typedText, setTypedText] = useState("");
        const [showSecret, setShowSecret] = useState(false);
          const [openGift, setOpenGift] = useState(false);
            const [noPosition, setNoPosition] = useState({ top: "60%", left: "60%" });

              const audioRef = useRef<HTMLAudioElement | null>(null);

                const message =
                    "You did it! Yayyyy you pressed the right button! Thank you actually for being YOU! and keep being YOU, and do the best. I'll be here, I'll make sure to make you the happiest girl in the whole world. It's a childish thing but hey I'm willing to do it! Thank you! Have a nice day!.";

                      // Start experience
                        const startExperience = () => {
                            if (!started) {
                                  setStarted(true);
                                        if (audioRef.current) {
                                                audioRef.current.play();
                                                      }
                                                          }
                                                            };

                                                              // Typing animation
                                                                useEffect(() => {
                                                                    if (accepted) {
                                                                          let i = 0;
                                                                                const interval = setInterval(() => {
                                                                                        setTypedText(message.slice(0, i));
                                                                                                i++;
                                                                                                        if (i > message.length) {
                                                                                                                  clearInterval(interval);
                                                                                                                            setShowSecret(true);
                                                                                                                                    }
                                                                                                                                          }, 30);
                                                                                                                                                return () => clearInterval(interval);
                                                                                                                                                    }
                                                                                                                                                      }, [accepted]);

                                                                                                                                                        // Floating hearts
                                                                                                                                                          useEffect(() => {
                                                                                                                                                              if (!started) return;

                                                                                                                                                                  const createHeart = () => {
                                                                                                                                                                        const heart = document.createElement("div");
                                                                                                                                                                              heart.innerHTML = "💖";
                                                                                                                                                                                    heart.className = "heart";
                                                                                                                                                                                          heart.style.left = Math.random() * 100 + "vw";
                                                                                                                                                                                                heart.style.fontSize = Math.random() * 15 + 20 + "px";
                                                                                                                                                                                                      document.body.appendChild(heart);
                                                                                                                                                                                                            setTimeout(() => heart.remove(), 6000);
                                                                                                                                                                                                                };

                                                                                                                                                                                                                    const interval = setInterval(createHeart, 800);
                                                                                                                                                                                                                        return () => clearInterval(interval);
                                                                                                                                                                                                                          }, [started]);

                                                                                                                                                                                                                            // Move NO button
                                                                                                                                                                                                                              const moveNoButton = (e: any) => {
                                                                                                                                                                                                                                  e.stopPropagation();
                                                                                                                                                                                                                                      const randomTop = Math.random() * 80 + "%";
                                                                                                                                                                                                                                          const randomLeft = Math.random() * 80 + "%";
                                                                                                                                                                                                                                              setNoPosition({ top: randomTop, left: randomLeft });
                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                            className={started ? "container active" : "container"}
                                                                                                                                                                                                                                                                  onClick={startExperience}
                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                            <audio ref={audioRef} src="/herewithme.mp3" loop />

                                                                                                                                                                                                                                                                                  {!started && (
                                                                                                                                                                                                                                                                                          <div className="start-screen fade">
                                                                                                                                                                                                                                                                                                    <h1>Ronita</h1>
                                                                                                                                                                                                                                                                                                              <p>Tap anywhere to start ✨</p>
                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                  {started && !accepted && (
                                                                                                                                                                                                                                                                                                                                          <div className="main fade">
                                                                                                                                                                                                                                                                                                                                                    <h1 className="title">Hey Ronita</h1>
                                                                                                                                                                                                                                                                                                                                                              <h2>Will you press the right button?</h2>

                                                                                                                                                                                                                                                                                                                                                                        <div className="button-group">
                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                  className="yes-btn"
                                                                                                                                                                                                                                                                                                                                                                                                                onClick={(e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                e.stopPropagation();
                                                                                                                                                                                                                                                                                                                                                                                                                                                setAccepted(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Yes 💫
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="no-btn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ top: noPosition.top, left: noPosition.left }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onMouseEnter={moveNoButton}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={moveNoButton}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  No 🙃
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {accepted && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="message-box fade">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h1 className="success">You said YES Ronita ✨</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="typing">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {typedText}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="cursor">|</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {showSecret && !openGift && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="secret-btn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={(e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            e.stopPropagation();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setOpenGift(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Open Secret 🎁
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {openGift && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flowers">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              🌸 🌷 🌹 🌺 🌻 🌼 🌸 🌷 🌹 🌺
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="footer">from Elbanan ✨</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }